[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'


[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

#Colorscheme
[[plugins]]
repo='cormacrelf/vim-colors-github'

[[plugins]]
repo='yous/vim-open-color'

[[plugins]]
repo='relastle/bluewery.vim'


#comment out
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source="""
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
  \ 'nofile_complete_filetypes': ['zsh'],
  \ })
"""

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo='mattn/vim-lsp-settings'


[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='lambdalisue/gina.vim'

# [[plugins]]
# repo='nvim-treesitter/nvim-treesitter'
# hook_source="""
# lua<<EOF
# require'nvim-treesitter.configs'.setup{
#   highlight={
#     enable=true,
#   },
#   ensure_installed = 'maintained',
# }
# EOF
# """

[[plugins]]
repo='hrsh7th/vim-vsnip'
hook_source="""
let g:vsnip_snippet_dir = $HOME .. "/config/vim/snippets/"
"""

[[plugins]]
repo='hrsh7th/vim-vsnip-integ'

[[plugins]]
repo="y0za/vim-reading-vimrc"
