[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'

[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo='folke/tokyonight.nvim'
hook_source="""
let g:tokyonight_style = "storm"
"""

#comment out
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source="""
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
  \ 'nofile_complete_filetypes': ['zsh'],
  \ })
"""

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo='mattn/vim-lsp-settings'

# [[plugins]]
# repo='nvim-treesitter/nvim-treesitter'
# hook_source="""
# lua<<EOF
# require'nvim-treesitter.configs'.setup{
#   highlight={
#     enable=true,
#   },
#   ensure_installed = 'maintained',
# }
# EOF
# """

[[plugins]]
repo='hrsh7th/vim-vsnip'
hook_source="""
let g:vsnip_snippet_dir = $HOME .. "/config/vim/snippets/"
"""

[[plugins]]
repo='hrsh7th/vim-vsnip-integ'

[[plugins]]
repo='nvim-lua/plenary.nvim'

[[plugins]]
repo='folke/todo-comments.nvim'
hook_source="""
lua << EOF
  require("todo-comments").setup {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
    keywords = {
      hasu = {icon = "ï¡§ ", color = "hint"}
    }
  }
EOF
"""

[[plugins]]
repo='Shougo/context_filetype.vim'

[[plugins]]
repo='osyo-manga/vim-precious'

[[plugins]]
repo='machakann/vim-sandwich'

# [[plugins]]
# repo='Shougo/ddc.vim'
[[plugins]]
repo='vim-denops/denops.vim'
