[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'


[[plugins]]
repo = 'mattn/vim-lexiv'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

#Colorscheme
[[plugins]]
repo='ghifarit53/tokyonight-vim'


# [[plugins]]
# repo = "tyru/open-browser.vim"
# hook_add ="""
# let g:openbrowser_browser_commands = [
# \ {"name":'open',
# \ "args": ["{browser}","{uri}"]}]
# """


#Highlight url
# [[plugins]]
# repo = 'itchyny/vim-highlighturl'


#comment out
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add ="""
let g:neosnippet#snippets_directory='~/dotfiles/vim/snippets/'
"""


[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source="""
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
  \ 'nofile_complete_filetypes': ['zsh'],
  \ })
"""

[[plugins]]
repo='prabirshrestha/vim-lsp'

[[plugins]]
repo='mattn/vim-lsp-settings'


[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='lambdalisue/gina.vim'
